apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-cave
spec:
  selector:
    matchLabels:
      app: demo-cave
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-cave
    spec:
      containers:
      - name: demo-cave
        image: paulcgz/demo-cave:0.0.1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "256M"
          requests:
            cpu: "0.5"
            memory: "128M"
